apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-service.fullname" . }}
  labels:
    {{- include "application-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "application-service.selectorLabels" . | nindent 4 }}
